import { useEffect, useMemo, useState } from 'react'
import { Check, ClipboardList, X } from 'lucide-react'
import { PageHeader } from '../../components/layout/page-header'
import { Card, CardContent } from '../../components/ui/card'
import { Button } from '../../components/ui/button'
import { StatusBadge } from '../../components/ui/status-badge'
import { repository } from '../../data/mock/mock-repository'
import type { ApplicationStatus, HousingApplication } from '../../lib/types'
import { formatDate } from '../../lib/utils'

export function ApplicationsPage() {
  const [items, setItems] = useState<HousingApplication[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | ApplicationStatus>('all')
  useEffect(() => { repository.listApplications().then(setItems) }, [])
  const filtered = useMemo(() => items.filter((item) => (status === 'all' || item.status === status) && `${item.studentName} ${item.studentCode} ${item.preferredBuilding}`.toLowerCase().includes(query.toLowerCase())), [items, query, status])
  async function update(id: string, next: ApplicationStatus) { const item = await repository.updateApplicationStatus(id, next); setItems((current) => current.map((row) => row.id === id ? item : row)) }
  return <><PageHeader title="Đăng ký ở" description="Tiếp nhận và xử lý hồ sơ đăng ký chỗ ở của sinh viên." actions={<Button><ClipboardList size={16} /> Xuất danh sách</Button>} /><div className="kpi-grid compact-kpis"><Summary label="Tổng hồ sơ" value={items.length} /><Summary label="Chờ duyệt" value={items.filter((item) => item.status === 'pending').length} tone="warning" /><Summary label="Đã duyệt" value={items.filter((item) => item.status === 'approved').length} tone="success" /><Summary label="Từ chối" value={items.filter((item) => item.status === 'rejected').length} tone="danger" /></div><div className="card"><div className="table-toolbar"><div className="toolbar-controls"><input className="field-control" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm sinh viên, mã đơn..." aria-label="Tìm đơn đăng ký" /><select className="select-control" value={status} onChange={(event) => setStatus(event.target.value as typeof status)} aria-label="Lọc trạng thái"><option value="all">Tất cả trạng thái</option><option value="pending">Chờ duyệt</option><option value="approved">Đã duyệt</option><option value="rejected">Từ chối</option></select></div><span className="table-count">{filtered.length} hồ sơ</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Hồ sơ</th><th>Sinh viên</th><th>Nguyện vọng</th><th>Ngày gửi</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><div className="cell-primary">{item.applicationCode}</div><div className="cell-secondary">Nhận {formatDate(item.expectedMoveIn)}</div></td><td><div className="cell-primary">{item.studentName}</div><div className="cell-secondary">{item.studentCode}</div></td><td>{item.preferredBuilding} · {item.preferredRoomType}</td><td>{formatDate(item.submittedAt)}</td><td><StatusBadge status={item.status} /></td><td><div className="action-group">{item.status === 'pending' && <><Button size="sm" onClick={() => update(item.id, 'approved')} aria-label={`Duyệt ${item.applicationCode}`}><Check size={14} /> Duyệt</Button><Button size="sm" variant="danger" onClick={() => update(item.id, 'rejected')} aria-label={`Từ chối ${item.applicationCode}`}><X size={14} /></Button></>}</div></td></tr>)}</tbody></table></div>{filtered.length === 0 && <div className="empty-state">Không có hồ sơ phù hợp.</div>}</div></>
}
function Summary({ label, value, tone = 'primary' }: { label: string; value: number; tone?: string }) { return <Card><CardContent className="summary-card"><span className={`kpi-icon ${tone}`}><ClipboardList size={18} /></span><div><span className="kpi-label">{label}</span><strong className="summary-value">{value}</strong></div></CardContent></Card> }
