import { useState } from 'react'
import { Dialog, DialogActions } from '../ui/dialog'
import { FormField } from '../ui/form-field'
import { repository } from '../../data/mock/mock-repository'
import type { HelpRequest, MaintenancePriority } from '../../lib/types'

export function HelpRequestDialog({ open, onClose, onSubmitted }: { open: boolean; onClose: () => void; onSubmitted?: (request: HelpRequest) => void }) {
  const [form, setForm] = useState({ category: 'Cơ sở vật chất' as HelpRequest['category'], subject: '', description: '', priority: 'Trung bình' as MaintenancePriority }); const [error, setError] = useState('')
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit() { if (!form.subject || !form.description) { setError('Nhập chủ đề và nội dung yêu cầu.'); return } const item = await repository.createHelpRequest(form); onSubmitted?.(item); setForm({ category: 'Cơ sở vật chất', subject: '', description: '', priority: 'Trung bình' }); setError(''); onClose() }
  return <Dialog open={open} title="Gửi yêu cầu hỗ trợ" description="Đội vận hành sẽ tiếp nhận và phản hồi yêu cầu của bạn." onClose={() => { setError(''); onClose() }} footer={<DialogActions onCancel={onClose} onSubmit={submit} submitLabel="Gửi yêu cầu" />}><div className="form-grid"><div className="form-field"><label className="form-label" htmlFor="help-category">Nhóm yêu cầu</label><select id="help-category" className="form-input" value={form.category} onChange={(event) => update('category', event.target.value)}><option>Cơ sở vật chất</option><option>Tài khoản</option><option>Hóa đơn</option><option>Khác</option></select></div><div className="form-field"><label className="form-label" htmlFor="help-priority">Mức độ</label><select id="help-priority" className="form-input" value={form.priority} onChange={(event) => update('priority', event.target.value)}><option>Thấp</option><option>Trung bình</option><option>Cao</option><option>Khẩn cấp</option></select></div><FormField label="Chủ đề" required value={form.subject} onChange={(event) => update('subject', event.target.value)} placeholder="Bạn cần hỗ trợ điều gì?" /><div className="form-field full"><label className="form-label" htmlFor="help-description">Nội dung <span className="required">*</span></label><textarea id="help-description" className="form-input" rows={4} value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="Mô tả chi tiết vấn đề..." /></div></div>{error && <p className="form-error" role="alert">{error}</p>}</Dialog>
}
