import { AlertCircle, CheckCircle2, Clock3, FileCheck2, FileWarning, Home, Wrench } from 'lucide-react'
import type { ReactNode } from 'react'

export type Status = 'active' | 'pending' | 'paid' | 'due' | 'overdue' | 'available' | 'occupied' | 'full' | 'maintenance' | 'checked_out' | 'approved' | 'rejected' | 'draft' | 'expiring' | 'expired' | 'new' | 'in_progress' | 'closed'
type StatusBadgeProps = { status: Status; label?: string; showIcon?: boolean }
const config: Record<Status, { label: string; tone: string; icon: ReactNode }> = {
  active: { label: 'Đang ở', tone: 'success', icon: <CheckCircle2 size={13} /> }, pending: { label: 'Chờ duyệt', tone: 'warning', icon: <Clock3 size={13} /> }, paid: { label: 'Đã thanh toán', tone: 'success', icon: <CheckCircle2 size={13} /> }, due: { label: 'Chờ thanh toán', tone: 'warning', icon: <Clock3 size={13} /> }, overdue: { label: 'Quá hạn', tone: 'danger', icon: <AlertCircle size={13} /> }, available: { label: 'Còn chỗ', tone: 'success', icon: <Home size={13} /> }, occupied: { label: 'Đang ở', tone: 'info', icon: <Home size={13} /> }, full: { label: 'Đã đầy', tone: 'danger', icon: <Home size={13} /> }, maintenance: { label: 'Bảo trì', tone: 'neutral', icon: <Wrench size={13} /> }, checked_out: { label: 'Đã trả phòng', tone: 'neutral', icon: <CheckCircle2 size={13} /> }, approved: { label: 'Đã duyệt', tone: 'success', icon: <FileCheck2 size={13} /> }, rejected: { label: 'Từ chối', tone: 'danger', icon: <AlertCircle size={13} /> }, draft: { label: 'Bản nháp', tone: 'neutral', icon: <FileWarning size={13} /> }, expiring: { label: 'Sắp hết hạn', tone: 'warning', icon: <Clock3 size={13} /> }, expired: { label: 'Đã hết hạn', tone: 'danger', icon: <AlertCircle size={13} /> }, new: { label: 'Mới', tone: 'warning', icon: <Clock3 size={13} /> }, in_progress: { label: 'Đang xử lý', tone: 'info', icon: <Wrench size={13} /> }, closed: { label: 'Đã đóng', tone: 'success', icon: <CheckCircle2 size={13} /> },
}
export function StatusBadge({ status, label, showIcon = true }: StatusBadgeProps) { const item = config[status]; return <span className={`status-badge ${item.tone}`}>{showIcon && item.icon}<span>{label ?? item.label}</span></span> }
